import { db, jobsTable, coursesTable } from "@workspace/db";

const jobs = [
  {
    title: "Analista Administrativo",
    company: "Grupo Alfa Servicos",
    location: "Sao Paulo, SP",
    type: "clt",
    area: "Administracao",
    salaryMin: 2800,
    salaryMax: 3800,
    description: "Responsavel por suporte administrativo, controle de documentos, agendamento e atendimento interno. Trabalho hibrido 3x por semana.",
    requirements: JSON.stringify(["Ensino medio completo", "Experiencia minima de 1 ano em administrativo", "Conhecimento em pacote Office"]),
    skills: JSON.stringify(["Excel", "Word", "Atendimento ao cliente", "Organizacao", "Comunicacao"]),
    benefits: JSON.stringify(["Vale transporte", "Vale refeicao", "Plano de saude", "PLR"]),
    isActive: true,
  },
  {
    title: "Operador de Logistica",
    company: "TransBrasil Cargas",
    location: "Guarulhos, SP",
    type: "clt",
    area: "Logistica",
    salaryMin: 2200,
    salaryMax: 2800,
    description: "Separacao, conferencia e movimentacao de mercadorias. Controle de estoque via sistema WMS. Turno fixo diurno.",
    requirements: JSON.stringify(["Ensino medio completo", "Disponibilidade para trabalho em turno", "Experiencia em deposito ou logistica"]),
    skills: JSON.stringify(["Logistica", "Controle de estoque", "WMS", "Trabalho em equipe"]),
    benefits: JSON.stringify(["Vale transporte", "Vale alimentacao", "Seguro de vida", "Adicional de turno"]),
    isActive: true,
  },
  {
    title: "Assistente Financeiro",
    company: "Contabilidade Modelo Ltda",
    location: "Santo Andre, SP",
    type: "clt",
    area: "Financeiro",
    salaryMin: 3000,
    salaryMax: 4200,
    description: "Controle de contas a pagar e receber, conciliacao bancaria, emissao de boletos e relatorios financeiros mensais.",
    requirements: JSON.stringify(["Curso tecnico ou superior em Contabilidade/Financas", "Conhecimento em Excel avancado", "Experiencia minima de 6 meses"]),
    skills: JSON.stringify(["Excel", "Conciliacao bancaria", "Contas a pagar", "Contas a receber", "ERP"]),
    benefits: JSON.stringify(["Vale transporte", "Vale refeicao", "Plano odontologico", "Gympass"]),
    isActive: true,
  },
  {
    title: "Tecnico de Manutencao Eletrica",
    company: "Industria Metalica Nacional",
    location: "Osasco, SP",
    type: "clt",
    area: "Industria",
    salaryMin: 4000,
    salaryMax: 5500,
    description: "Manutencao preventiva e corretiva de maquinas industriais, paineis eletricos e sistemas de automacao. Atuacao em fabrica de grande porte.",
    requirements: JSON.stringify(["Tecnico em Eletrotecnica ou Eletrica", "NR10 e NR35 atualizados", "Experiencia com CLP e inversores de frequencia"]),
    skills: JSON.stringify(["Eletrica industrial", "CLP", "Automacao", "Manutencao preventiva", "NR10"]),
    benefits: JSON.stringify(["Vale transporte", "Refeicao no local", "Plano de saude", "Adicional de insalubridade"]),
    isActive: true,
  },
  {
    title: "Atendente de Loja",
    company: "Rede Moda Brasil",
    location: "Campinas, SP",
    type: "clt",
    area: "Varejo",
    salaryMin: 1800,
    salaryMax: 2400,
    description: "Atendimento ao cliente, organizacao da loja, controle de estoque e suporte ao caixa. Trabalho em escala 6x1.",
    requirements: JSON.stringify(["Ensino medio completo", "Boa comunicacao", "Disponibilidade para trabalhar aos fins de semana"]),
    skills: JSON.stringify(["Atendimento ao cliente", "Vendas", "Organizacao", "Comunicacao"]),
    benefits: JSON.stringify(["Vale transporte", "Vale refeicao", "Comissao sobre vendas", "Desconto em produtos"]),
    isActive: true,
  },
  {
    title: "Auxiliar de Recursos Humanos",
    company: "Grupo Santana RH",
    location: "Sao Paulo, SP",
    type: "clt",
    area: "Recursos Humanos",
    salaryMin: 2400,
    salaryMax: 3200,
    description: "Apoio no processo de recrutamento e selecao, admissao, controle de ponto e beneficios. Trabalho 100% presencial.",
    requirements: JSON.stringify(["Cursando ou formado em Gestao de RH, Psicologia ou ADM", "Conhecimento em CLT", "Excel intermediario"]),
    skills: JSON.stringify(["Recrutamento", "CLT", "Excel", "Atendimento", "Organizacao"]),
    benefits: JSON.stringify(["Vale transporte", "Vale refeicao", "Plano de saude", "Universidade corporativa"]),
    isActive: true,
  },
  {
    title: "Desenvolvedor Web Junior",
    company: "StartUp Digital SP",
    location: "Sao Paulo, SP (Remoto)",
    type: "clt",
    area: "Tecnologia",
    salaryMin: 3500,
    salaryMax: 5000,
    description: "Desenvolvimento de interfaces web com React e integracao com APIs REST. Trabalho 100% remoto com equipe jovem e dinamica.",
    requirements: JSON.stringify(["Conhecimento em HTML, CSS e JavaScript", "Experiencia basica com React", "Git/GitHub"]),
    skills: JSON.stringify(["HTML", "CSS", "JavaScript", "React", "Git"]),
    benefits: JSON.stringify(["Vale refeicao", "Plano de saude", "Home office", "Stock options"]),
    isActive: true,
  },
  {
    title: "Vendedor Externo",
    company: "Distribuidora Horizonte",
    location: "Regiao de SP",
    type: "clt",
    area: "Vendas",
    salaryMin: 2500,
    salaryMax: 5000,
    description: "Prospectar novos clientes, apresentar produtos e fechar contratos na regiao metropolitana de Sao Paulo. Carro fornecido pela empresa.",
    requirements: JSON.stringify(["CNH categoria B", "Experiencia em vendas externas", "Facilidade com negociacao"]),
    skills: JSON.stringify(["Vendas", "Negociacao", "Prospecao", "CRM", "Comunicacao"]),
    benefits: JSON.stringify(["Carro da empresa", "Combustivel", "Comissao", "Plano de saude"]),
    isActive: true,
  },
];

const courses = [
  {
    title: "Excel do Zero ao Avancado",
    provider: "SENAC",
    area: "Administracao",
    level: "iniciante",
    durationHours: 40,
    description: "Aprenda todas as funcionalidades do Excel para uso profissional: formulas, tabelas dinamicas, macros e graficos. Certificado reconhecido pelo mercado.",
    skills: JSON.stringify(["Excel", "Planilhas", "Analise de dados", "Graficos"]),
    url: "https://www.senac.br",
    isFree: "false",
  },
  {
    title: "Logistica e Supply Chain",
    provider: "SEBRAE",
    area: "Logistica",
    level: "intermediario",
    durationHours: 20,
    description: "Conceitos fundamentais de logistica, cadeia de suprimentos, gestao de estoque e distribuicao para pequenas e medias empresas.",
    skills: JSON.stringify(["Logistica", "Supply chain", "Controle de estoque", "Distribuicao"]),
    url: "https://www.sebrae.com.br",
    isFree: "true",
  },
  {
    title: "Comunicacao e Atendimento ao Cliente",
    provider: "SENAI",
    area: "Varejo",
    level: "iniciante",
    durationHours: 16,
    description: "Tecnicas de comunicacao eficaz, resolucao de conflitos e fidelizacao de clientes. Ideal para quem trabalha ou quer trabalhar no comercio.",
    skills: JSON.stringify(["Comunicacao", "Atendimento ao cliente", "Vendas", "Relacionamento"]),
    url: "https://www.senai.br",
    isFree: "true",
  },
  {
    title: "Tecnico em Seguranca do Trabalho",
    provider: "SENAC",
    area: "Industria",
    level: "intermediario",
    durationHours: 120,
    description: "Formacao tecnica em seguranca e saude no trabalho, NRs, analise de riscos e implantacao de CIPA. Certificado de nivel tecnico.",
    skills: JSON.stringify(["NR10", "NR35", "Seguranca do trabalho", "CIPA", "Analise de riscos"]),
    url: "https://www.senac.br",
    isFree: "false",
  },
  {
    title: "Gestao Financeira para Pequenas Empresas",
    provider: "SEBRAE",
    area: "Financeiro",
    level: "iniciante",
    durationHours: 8,
    description: "Controle de fluxo de caixa, conciliacao bancaria, planejamento financeiro e como separar financas pessoais das empresariais.",
    skills: JSON.stringify(["Financas", "Fluxo de caixa", "Conciliacao bancaria", "Planejamento financeiro"]),
    url: "https://www.sebrae.com.br",
    isFree: "true",
  },
  {
    title: "HTML e CSS para Iniciantes",
    provider: "Coursera - Google",
    area: "Tecnologia",
    level: "iniciante",
    durationHours: 30,
    description: "Crie suas primeiras paginas web com HTML e CSS. Aprenda a estrutura basica de sites e estilizacao responsiva. Certificado Google.",
    skills: JSON.stringify(["HTML", "CSS", "Web design", "Responsivo"]),
    url: "https://www.coursera.org",
    isFree: "false",
  },
  {
    title: "Recrutamento e Selecao na Pratica",
    provider: "FGV Online",
    area: "Recursos Humanos",
    level: "intermediario",
    durationHours: 25,
    description: "Tecnicas de entrevista, triagem de curriculos, avaliacao por competencias e uso de ferramentas digitais de recrutamento.",
    skills: JSON.stringify(["Recrutamento", "Selecao", "Entrevista", "RH", "Gestao de pessoas"]),
    url: "https://eadbox.fgv.br",
    isFree: "false",
  },
  {
    title: "Tecnicas de Vendas e Negociacao",
    provider: "SENAC",
    area: "Vendas",
    level: "iniciante",
    durationHours: 20,
    description: "Estrategias de prospecao, abordagem, apresentacao de produto, tratamento de objecoes e fechamento de vendas. Pratico e objetivo.",
    skills: JSON.stringify(["Vendas", "Negociacao", "Prospecao", "Fechamento", "Comunicacao"]),
    url: "https://www.senac.br",
    isFree: "false",
  },
  {
    title: "Power BI para Analise de Dados",
    provider: "Microsoft Learn",
    area: "Administracao",
    level: "intermediario",
    durationHours: 15,
    description: "Criacao de dashboards e relatorios interativos com Power BI. Transforme dados brutos em insights visuais para tomada de decisao.",
    skills: JSON.stringify(["Power BI", "Analise de dados", "Dashboard", "Excel", "Business intelligence"]),
    url: "https://learn.microsoft.com",
    isFree: "true",
  },
  {
    title: "Introducao ao Python",
    provider: "Fundacao Bradesco",
    area: "Tecnologia",
    level: "iniciante",
    durationHours: 36,
    description: "Aprenda programacao com Python do zero. Variaveis, funcoes, estruturas de dados e automacao de tarefas. Certificado gratuito.",
    skills: JSON.stringify(["Python", "Programacao", "Automacao", "Logica de programacao"]),
    url: "https://www.ev.org.br",
    isFree: "true",
  },
];

async function seed() {
  console.log("Seeding jobs...");
  await db.delete(jobsTable);
  await db.insert(jobsTable).values(jobs);
  console.log(`Inserted ${jobs.length} jobs.`);

  console.log("Seeding courses...");
  await db.delete(coursesTable);
  await db.insert(coursesTable).values(courses);
  console.log(`Inserted ${courses.length} courses.`);

  console.log("Done!");
  process.exit(0);
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
